name: "Lint"

on:
  workflow_call:
  pull_request:
    branches: [ master ]


jobs:
  lint:
    name: Run lint check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PyLint
      run: pip install pylint

    - name: Run linting check
      run: pylint --recursive=y ./horovod --reports=True
      shell: bash
